# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

doSomethingWithTest <- function(test) {
    .Call(`_distMod_doSomethingWithTest`, test)
}

getTest <- function(a, b) {
    .Call(`_distMod_getTest`, a, b)
}

