# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

useLinearModel <- function(X, y) {
    .Call(`_distMod_useLinearModel`, X, y)
}

testLinearModel <- function(modelptr, beta) {
    .Call(`_distMod_testLinearModel`, modelptr, beta)
}

doSomethingWithTest <- function(test) {
    .Call(`_distMod_doSomethingWithTest`, test)
}

getTest <- function(a, b) {
    .Call(`_distMod_getTest`, a, b)
}

